server:
  port: 8081

spring:
  application:
    name: courier-service
  datasource:
    url: jdbc:postgresql://localhost:5433/courierdb
    username: user
    password: pass
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: courier-service-group
      auto-offset-reset: earliest        # servisi yeniden baslatinca kacirdigi mesajlari okusun
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"   # ShipmentAssignedEvent deserialize icin

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
